# Site settings
title: Python-Sprints
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Python-Sprints is a non profit organisation gathering Python programmers and helping improve code in open source projects.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://python-sprints.github.io/" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  python-sprints

# Build settings
include: ['_pages']
sass:
  sass_dir: _sass
kramdown:
  input: GFM
include: ["_test.html", "_static", "pandas/guide/_static", "_pages"]
#include: ["_pages"]
exclude:
  - Gemfile
  - Gemfile.lock
  - static/images/sources/
  - _pages/02_get_started.html
  - DOCS/
future: true

collections:
  sponsors:
    output: false
  chapters:
      output: true

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      is_post: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# command to run build locally:
# bundle exec jekyll serve --host 0.0.0.0 --config _config.yml,_config_dev.yml